# CMake generated Testfile for 
# Source directory: /Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control
# Build directory: /Users/yukun/ns-allinone-3.42/ns-3.42/cmake-cache/examples/traffic-control
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-traffic-control "ns3.42-traffic-control-default")
set_tests_properties(ctest-traffic-control PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;1;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-queue-discs-benchmark "ns3.42-queue-discs-benchmark-default")
set_tests_properties(ctest-queue-discs-benchmark PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;12;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-fengadaptive "ns3.42-red-vs-fengadaptive-default")
set_tests_properties(ctest-red-vs-fengadaptive PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;24;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-nlred "ns3.42-red-vs-nlred-default")
set_tests_properties(ctest-red-vs-nlred PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;35;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-tbf-example "ns3.42-tbf-example-default")
set_tests_properties(ctest-tbf-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;46;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-cobalt-vs-codel "ns3.42-cobalt-vs-codel-default")
set_tests_properties(ctest-cobalt-vs-codel PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;56;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/traffic-control/CMakeLists.txt;0;")
