# CMake generated Testfile for 
# Source directory: /Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples
# Build directory: /Users/yukun/ns-allinone-3.42/ns-3.42/cmake-cache/src/energy/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-generic-battery-discharge-example "ns3.42-generic-battery-discharge-example-default")
set_tests_properties(ctest-generic-battery-discharge-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;1;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-generic-battery-wifiradio-example "ns3.42-generic-battery-wifiradio-example-default")
set_tests_properties(ctest-generic-battery-wifiradio-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;8;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-li-ion-energy-source-example "ns3.42-li-ion-energy-source-example-default")
set_tests_properties(ctest-li-ion-energy-source-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;20;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-rv-battery-model-test "ns3.42-rv-battery-model-test-default")
set_tests_properties(ctest-rv-battery-model-test PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;27;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-basic-energy-model-test "ns3.42-basic-energy-model-test-default")
set_tests_properties(ctest-basic-energy-model-test PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;36;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/energy/examples/CMakeLists.txt;0;")
