# CMake generated Testfile for 
# Source directory: /Users/yukun/ns-allinone-3.42/ns-3.42/src/internet-apps/examples
# Build directory: /Users/yukun/ns-allinone-3.42/ns-3.42/cmake-cache/src/internet-apps/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dhcp-example "ns3.42-dhcp-example-default")
set_tests_properties(ctest-dhcp-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/internet-apps/examples/CMakeLists.txt;1;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/internet-apps/examples/CMakeLists.txt;0;")
add_test(ctest-traceroute-example "ns3.42-traceroute-example-default")
set_tests_properties(ctest-traceroute-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/internet-apps/examples/CMakeLists.txt;12;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/internet-apps/examples/CMakeLists.txt;0;")
add_test(ctest-ping-example "ns3.42-ping-example-default")
set_tests_properties(ctest-ping-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/internet-apps/examples/CMakeLists.txt;25;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/internet-apps/examples/CMakeLists.txt;0;")
