# CMake generated Testfile for 
# Source directory: /Users/yukun/ns-allinone-3.42/ns-3.42/src/buildings/examples
# Build directory: /Users/yukun/ns-allinone-3.42/ns-3.42/cmake-cache/src/buildings/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-buildings-pathloss-profiler "ns3.42-buildings-pathloss-profiler-default")
set_tests_properties(ctest-buildings-pathloss-profiler PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/buildings/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/buildings/examples/CMakeLists.txt;1;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/buildings/examples/CMakeLists.txt;0;")
add_test(ctest-outdoor-group-mobility-example "ns3.42-outdoor-group-mobility-example-default")
set_tests_properties(ctest-outdoor-group-mobility-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/buildings/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/buildings/examples/CMakeLists.txt;11;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/buildings/examples/CMakeLists.txt;0;")
add_test(ctest-outdoor-random-walk-example "ns3.42-outdoor-random-walk-example-default")
set_tests_properties(ctest-outdoor-random-walk-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/buildings/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/buildings/examples/CMakeLists.txt;17;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/buildings/examples/CMakeLists.txt;0;")
