# CMake generated Testfile for 
# Source directory: /Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial
# Build directory: /Users/yukun/ns-allinone-3.42/ns-3.42/cmake-cache/examples/tutorial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-hello-simulator "ns3.42-hello-simulator-default")
set_tests_properties(ctest-hello-simulator PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/tutorial/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;1;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-first "ns3.42-first-default")
set_tests_properties(ctest-first PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/tutorial/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;7;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-second "ns3.42-second-default")
set_tests_properties(ctest-second PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/tutorial/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;17;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-third "ns3.42-third-default")
set_tests_properties(ctest-third PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/tutorial/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;28;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fourth "ns3.42-fourth-default")
set_tests_properties(ctest-fourth PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/tutorial/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;40;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fifth "ns3.42-fifth-default")
set_tests_properties(ctest-fifth PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/tutorial/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;46;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-sixth "ns3.42-sixth-default")
set_tests_properties(ctest-sixth PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/tutorial/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;57;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-seventh "ns3.42-seventh-default")
set_tests_properties(ctest-seventh PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/tutorial/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;68;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/tutorial/CMakeLists.txt;0;")
