# CMake generated Testfile for 
# Source directory: /Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6
# Build directory: /Users/yukun/ns-allinone-3.42/ns-3.42/cmake-cache/examples/ipv6
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-fragmentation-ipv6 "ns3.42-fragmentation-ipv6-default")
set_tests_properties(ctest-fragmentation-ipv6 PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;1;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-fragmentation-ipv6-two-MTU "ns3.42-fragmentation-ipv6-two-MTU-default")
set_tests_properties(ctest-fragmentation-ipv6-two-MTU PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;10;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-icmpv6-redirect "ns3.42-icmpv6-redirect-default")
set_tests_properties(ctest-icmpv6-redirect PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;19;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-loose-routing-ipv6 "ns3.42-loose-routing-ipv6-default")
set_tests_properties(ctest-loose-routing-ipv6 PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;28;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-ping6-example "ns3.42-ping6-example-default")
set_tests_properties(ctest-ping6-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;37;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-radvd-one-prefix "ns3.42-radvd-one-prefix-default")
set_tests_properties(ctest-radvd-one-prefix PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;46;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-radvd-two-prefix "ns3.42-radvd-two-prefix-default")
set_tests_properties(ctest-radvd-two-prefix PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;55;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-test-ipv6 "ns3.42-test-ipv6-default")
set_tests_properties(ctest-test-ipv6 PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;64;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-wsn-ping6 "ns3.42-wsn-ping6-default")
set_tests_properties(ctest-wsn-ping6 PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;71;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-fragmentation-ipv6-PMTU "ns3.42-fragmentation-ipv6-PMTU-default")
set_tests_properties(ctest-fragmentation-ipv6-PMTU PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/examples/ipv6/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;82;build_example;/Users/yukun/ns-allinone-3.42/ns-3.42/examples/ipv6/CMakeLists.txt;0;")
