# CMake generated Testfile for 
# Source directory: /Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples
# Build directory: /Users/yukun/ns-allinone-3.42/ns-3.42/cmake-cache/src/lr-wpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-lr-wpan-data "ns3.42-lr-wpan-data-default")
set_tests_properties(ctest-lr-wpan-data PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-mlme "ns3.42-lr-wpan-mlme-default")
set_tests_properties(ctest-lr-wpan-mlme PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-packet-print "ns3.42-lr-wpan-packet-print-default")
set_tests_properties(ctest-lr-wpan-packet-print PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-phy-test "ns3.42-lr-wpan-phy-test-default")
set_tests_properties(ctest-lr-wpan-phy-test PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-ed-scan "ns3.42-lr-wpan-ed-scan-default")
set_tests_properties(ctest-lr-wpan-ed-scan PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-active-scan "ns3.42-lr-wpan-active-scan-default")
set_tests_properties(ctest-lr-wpan-active-scan PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-orphan-scan "ns3.42-lr-wpan-orphan-scan-default")
set_tests_properties(ctest-lr-wpan-orphan-scan PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-error-distance-plot "ns3.42-lr-wpan-error-distance-plot-default")
set_tests_properties(ctest-lr-wpan-error-distance-plot PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;22;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-error-model-plot "ns3.42-lr-wpan-error-model-plot-default")
set_tests_properties(ctest-lr-wpan-error-model-plot PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;29;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-bootstrap "ns3.42-lr-wpan-bootstrap-default")
set_tests_properties(ctest-lr-wpan-bootstrap PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;36;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-per-plot "ns3.42-lr-wpan-per-plot-default")
set_tests_properties(ctest-lr-wpan-per-plot PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;43;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/lr-wpan/examples/CMakeLists.txt;0;")
