# CMake generated Testfile for 
# Source directory: /Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples
# Build directory: /Users/yukun/ns-allinone-3.42/ns-3.42/cmake-cache/src/uan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-uan-cw-example "ns3.42-uan-cw-example-default")
set_tests_properties(ctest-uan-cw-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-rc-example "ns3.42-uan-rc-example-default")
set_tests_properties(ctest-uan-rc-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-ipv4-example "ns3.42-uan-ipv4-example-default")
set_tests_properties(ctest-uan-ipv4-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-ipv6-example "ns3.42-uan-ipv6-example-default")
set_tests_properties(ctest-uan-ipv6-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-raw-example "ns3.42-uan-raw-example-default")
set_tests_properties(ctest-uan-raw-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;12;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-6lowpan-example "ns3.42-uan-6lowpan-example-default")
set_tests_properties(ctest-uan-6lowpan-example PROPERTIES  WORKING_DIRECTORY "/Users/yukun/ns-allinone-3.42/ns-3.42/build/src/uan/examples/" _BACKTRACE_TRIPLES "/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/Users/yukun/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;24;build_lib_example;/Users/yukun/ns-allinone-3.42/ns-3.42/src/uan/examples/CMakeLists.txt;0;")
